/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ImHo59jyqN8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"

export function cart sidebar() {
  const [cartItems, setCartItems] = useState([
    {
      id: 1,
      name: "Cozy Fleece Pullover",
      price: 49.99,
      quantity: 1,
    },
    {
      id: 2,
      name: "Vintage Leather Backpack",
      price: 99.99,
      quantity: 1,
    },
    {
      id: 3,
      name: "Minimalist Desk Lamp",
      price: 29.99,
      quantity: 1,
    },
  ])
  const handleQuantityChange = (id, change) => {
    setCartItems((prevItems) =>
      prevItems.map((item) => (item.id === id ? { ...item, quantity: Math.max(item.quantity + change, 1) } : item)),
    )
  }
  const subtotal = cartItems.reduce((total, item) => total + item.price * item.quantity, 0)
  return (
    <div className="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col bg-background shadow-lg sm:w-auto">
      <div className="flex items-center justify-between border-b bg-card px-6 py-4">
        <h2 className="text-2xl font-bold">Your Cart</h2>
        <button className="rounded-full p-2 transition-colors hover:bg-muted" aria-label="Close cart">
          <XIcon className="h-5 w-5" />
        </button>
      </div>
      <div className="flex-1 overflow-y-auto px-6 py-4">
        {cartItems.length === 0 ? (
          <p className="text-center text-muted-foreground">Your cart is empty.</p>
        ) : (
          <ul className="space-y-4">
            {cartItems.map((item) => (
              <li
                key={item.id}
                className="grid grid-cols-[auto_1fr_auto] items-center gap-4 rounded-lg bg-card p-4 shadow-sm transition-all hover:bg-muted"
              >
                <div className="w-16 h-16 rounded-md bg-muted animate-pulse" />
                <div>
                  <h3 className="text-lg font-medium">{item.name}</h3>
                  <p className="text-muted-foreground">${item.price.toFixed(2)}</p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    className="rounded-full bg-muted p-2 transition-colors hover:bg-accent hover:text-accent-foreground"
                    onClick={() => handleQuantityChange(item.id, -1)}
                    aria-label="Decrease quantity"
                  >
                    <MinusIcon className="h-4 w-4" />
                  </button>
                  <span className="text-lg font-medium">{item.quantity}</span>
                  <button
                    className="rounded-full bg-muted p-2 transition-colors hover:bg-accent hover:text-accent-foreground"
                    onClick={() => handleQuantityChange(item.id, 1)}
                    aria-label="Increase quantity"
                  >
                    <PlusIcon className="h-4 w-4" />
                  </button>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
      <div className="border-t bg-card px-6 py-4">
        <div className="flex items-center justify-between">
          <p className="text-muted-foreground">Subtotal</p>
          <p className="text-2xl font-bold">
            ${subtotal.toFixed(2)}
            <span className="ml-2 text-lg font-normal text-muted-foreground">USD</span>
          </p>
        </div>
        <div className="mt-4 flex gap-2">
          <Button className="flex-1 bg-primary text-primary-foreground transition-all hover:bg-primary/90 focus:ring-2 focus:ring-primary/50 active:scale-95">
            Checkout
          </Button>
          <Button
            variant="outline"
            className="flex-1 transition-all hover:bg-muted focus:ring-2 focus:ring-muted/50 active:scale-95"
          >
            Clear Cart
          </Button>
        </div>
      </div>
    </div>
  )
}

function MinusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
