/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YClWRtXDYWD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function sellingpageVercel() {
  return (
    <div className="container mx-auto px-4 py-12 md:px-6 lg:px-8">
      <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        <div className="col-span-2 lg:col-span-1">
          <div className="grid gap-6">
            <div>
              <h2 className="text-3xl font-bold tracking-tight">Add New Product</h2>
              <p className="text-muted-foreground">Showcase your latest offerings.</p>
            </div>
            <div className="grid gap-4">
              <div>
                <Label htmlFor="image">Product Image</Label>
                <div className="mt-2 flex justify-center rounded-md border-2 border-dashed border-muted px-6 pt-5 pb-6">
                  <div className="space-y-1 text-center">
                    <UploadIcon className="mx-auto h-12 w-12 text-muted-foreground" />
                    <div className="flex text-sm text-muted-foreground">
                      <label
                        htmlFor="image"
                        className="relative cursor-pointer rounded-md bg-white font-medium text-primary focus-within:outline-none focus-within:ring-2 focus-within:ring-primary focus-within:ring-offset-2 hover:text-primary-foreground"
                      >
                        <span>Upload a file</span>
                        <Input id="image" type="file" className="sr-only" accept="image/*" />
                      </label>
                      <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-muted-foreground">PNG, JPG, GIF up to 10MB</p>
                  </div>
                </div>
                <div className="mt-2 flex justify-center">
                  <img
                    src="/placeholder.svg"
                    alt="Product Image"
                    width={300}
                    height={300}
                    className="max-w-full rounded-md object-cover"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-span-2 lg:col-span-2">
          <div className="grid gap-4">
            <div>
              <Label htmlFor="name">Product Name</Label>
              <Input
                id="name"
                type="text"
                placeholder="Enter product name"
                className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-lg font-bold shadow-sm focus:border-primary focus:ring-primary"
              />
            </div>
            <div>
              <Label htmlFor="description">Product Description</Label>
              <Textarea
                id="description"
                placeholder="Describe your product in detail"
                className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-base shadow-sm focus:border-primary focus:ring-primary"
                rows={5}
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="price">Price</Label>
                <div className="relative mt-1 rounded-md shadow-sm">
                  <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                    <span className="text-muted-foreground">$</span>
                  </div>
                  <Input
                    id="price"
                    type="number"
                    placeholder="0.00"
                    className="block w-full rounded-md border-input bg-background pl-7 pr-3 py-2 text-lg focus:border-primary focus:ring-primary"
                  />
                </div>
              </div>
              <div>
                <Label htmlFor="quantity">Quantity</Label>
                <Select
                  id="quantity"
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-base shadow-sm focus:border-primary focus:ring-primary"
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select quantity" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">1</SelectItem>
                    <SelectItem value="2">2</SelectItem>
                    <SelectItem value="3">3</SelectItem>
                    <SelectItem value="4">4</SelectItem>
                    <SelectItem value="5">5</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div>
              <Label htmlFor="category">Category</Label>
              <Select
                id="category"
                className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-base shadow-sm focus:border-primary focus:ring-primary"
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="clothing">Clothing</SelectItem>
                  <SelectItem value="electronics">Electronics</SelectItem>
                  <SelectItem value="home">Home</SelectItem>
                  <SelectItem value="outdoor">Outdoor</SelectItem>
                  <SelectItem value="toys">Toys</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="Enter email"
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-base shadow-sm focus:border-primary focus:ring-primary"
                />
              </div>
              <div>
                <Label htmlFor="phone">Phone</Label>
                <Input
                  id="phone"
                  type="tel"
                  placeholder="Enter phone number"
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-base shadow-sm focus:border-primary focus:ring-primary"
                />
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Checkbox id="available" />
              <Label htmlFor="available" className="text-base font-normal">
                Available
              </Label>
            </div>
            <Button
              type="submit"
              className="w-full rounded-md bg-primary px-4 py-2 text-lg font-medium text-primary-foreground shadow-sm hover:bg-primary-foreground hover:text-primary transition-colors"
            >
              Submit
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
